#version: '3'

services:
  mariadb:
    build:
      context: requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    container_name: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    secrets:
      - mariadb_db_password
      - mariadb_db_root_password
    restart: always

  wordpress:
    build:
      context: requirements/wordpress/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
    env_file:
      - .env
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    secrets:
      - wordpress_superpass
      - wordpress_simplepass
      - mariadb_db_password
      - mariadb_db_root_password
    depends_on:
      - mariadb
    restart: always
 
  nginx:
    build: requirements/nginx/
    container_name: nginx
    networks:
      - inception
    ports:
        - "443:443"
        - "80:80"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - ./requirements/bonus/website/tools:/portfolio
      - wp-volume:/var/www/
    depends_on:
      - wordpress
    restart: always

  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    ports:
      - "6379:6379"
    volumes:
      - rd-volume:/data
    restart: always
  
  ftp:
    build: requirements/bonus/ftp
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: ftp
    networks:
      - inception
    ports:
      - "21:21"
      - "6000-6100:6000-6100"
    volumes:
      - wp-volume:/var/www/
    secrets:
      - wordpress_simplepass
    depends_on:
      - wordpress
    restart: always

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

secrets:
  wordpress_superpass:
    file: ../secrets/wordpress/superpass.txt
  wordpress_simplepass:
    file: ../secrets/wordpress/simplepass.txt
  mariadb_db_password:
    file: ../secrets/mariadb/db_password.txt
  mariadb_db_root_password:
    file: ../secrets/mariadb/db_root_password.txt

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  rd-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/redis

networks:
  inception:
    driver: bridge
